# Generated by Django 2.1.1 on 2021-01-20 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0002_branches'),
    ]

    operations = [
        migrations.AddField(
            model_name='banks',
            name='_id',
            field=models.BigIntegerField(default=0),
        ),
    ]
